filme/urls.py
from django.urls import path, reverse_lazy
from .views import Homepage, Homefilmes, DetalhesFilme, Pesquisafilme, Paginaperfil, Criarconta
from django.contrib.auth import views as auth_view  # dei novo nome para não confundir com as outras views que existem

app_name = 'filme' # nome do app para chamar nas urls do projeto hashflix, e não do projeto filme

urlpatterns = [
    # path('', homepage),  # caminho padrão do site, sem parâmetro na url. estou incluindo uma view chamada homepage. ou seja, chama a função homepage no arquivo views.py. estrutura Function Based View
    path('', Homepage.as_view(), name='homepage'), # chamo a classe Homepage como uma view do arquivo views.py. estrutura Class Based View
    path('filmes/', Homefilmes.as_view(), name='homefilmes'), # caminho para a tela de filmes, chamando a classe Homefilmes. name é para chamar a url nas tags <a href>
    path('filmes/<int:pk>', DetalhesFilme.as_view(), name='detalhesfilme'),  # chave primária do filme que eu quero, já que vem do object do model Detalhesfilme. caminho para a tela de detalhe do filme
    path('pesquisa/', Pesquisafilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),  # LoginView é padrão do django, não precisei criar no views.py
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html', success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'), # uso a editarperfil porque as funcionalidades das páginas são as mesmas
]

hashflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # permite achar o caminho da pasta static
from django.conf.urls.static import static  # permite achar o caminho da pasta static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme')),  # essa path está sendo o caminho padrão do site. namespace filme engloba todas as urls do app filme (variável app_name criada no filme/urls.py)
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # link para os arquivos static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # link para os arquivos media

filme/models.py
from django.db import models
from django.utils import timezone  # permite utilizar a data atual de uma ação
from django.contrib.auth.models import AbstractUser # importo o usuário padrão do django para poder modificá-lo do meu jeito de criar usuário

# Create your models here. Meu banco de dados!

LISTA_CATEGORIAS = (   # necessária para o campo categoria. (1º o que armazena no banco, 2º o que aparece pro usuário)
    ("ANALISES", "Análises"),
    ("PROGRAMACAO", "Programação"),
    ("APRESENTACAO", "Apresentação"),
    ("OUTROS", "Outros"),
)

# criar o filme
class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')  # nome da pasta que armazena as imagens que o usuário criar dos filmes
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.titulo  # retorno na página de admin o atributo título, ao invés de aparecer Filme.object como nome


# criar episódios
class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE) # relação do episódio com o filme, o episódio só pode pertencer a um filme. o parâmetro é o nome da tabela que está criando a relação. related_name "cria" um campo na tabela Filme com todos os episódios que aquele filme tem. se eu deletar o Filme, deleto todos os episódios dele
    titulo = models.CharField(max_length=100)
    video = models.URLField() # se comporta como um link

    def __str__(self):
        return self.filme.titulo + " - " + self.titulo  # retorno na página de admin o atributo título, ao invés de aparecer Episodio.object como nome


class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField("Filme") # vários usuários podem ver um filme e um filme pode ser visto por vários usuários, passando a classe Filme

filme/forms.py
# página que eu criei para formulários

from django.contrib.auth.forms import UserCreationForm # formulário de criar usuário
from .models import Usuario
from django import forms


class FormHomepage(forms.Form): # personalizar o formulário padrão do django
    email = forms.EmailField(label=False)


class CriarContaForm(UserCreationForm):
    email = forms.EmailField() # adicionar o campo de email no banco de dados

    class Meta:   # obrigação do UserCreationForm para dizer o modelo de referência. Usuario é o nosso modelo próprio de gerenciar usuários
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')  # campos que serão exibidos no formulário quando criar uma conta

filme/views.py
from django.shortcuts import render, redirect, reverse  # renderiza uma página, redireciona para uma página, pega o link de uma página
from .models import Filme, Usuario
from .forms import CriarContaForm, FormHomepage
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView # exibe templates, exibe listas, exibe detalhes de um item, exibe um formulário, reconhece a tabela que estou usando e carrega os campos que eu definir
from django.contrib.auth.mixins import LoginRequiredMixin # classe que bloqueia as classes da estrutura Class Based View que não estão logadas
                                                          # a autenticação do login está no settings.py

# Create your views here.

class Homepage(FormView): # herda a biblioteca FormView  # estrutura Class Based View # objetivo é mostrar uma view
    template_name = "homepage.html"  # nome do template que eu estou chamando com a classe
    form_class = FormHomepage

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated: # se o usuário está autenticado, redireciona para a homefilmes se tentar entrar na homepage. se não estiver logado, entra na homepage para fazer login
            return redirect('filme:homefilmes')  # não é carregar/render um template, é redirecionar para outra view. nome do app e nome da url definido em filme/urls.py
        else:
            return super().get(request, *args, **kwargs) # redireciona o usuário para a homepage

    def get_success_url(self):
        email = self.request.POST.get("email") # pega a informação passada do campo email vindo do post
        usuarios = Usuario.objects.filter(email=email) # verifica a lista de emails no banco de dados

        if usuarios:
            return reverse('filme: login') # se existir, manda pra página de login
        else:
            return reverse('filme:criarconta') # se não existir, manda pra página de criar conta


class Homefilmes(LoginRequiredMixin, ListView): # objetivo é exibir uma lista de itens
    template_name = "homefilmes.html"
    model = Filme  # model do banco de dados que eu quero pegar a lista. o nome da lista é padrão object_list. os objetos são de acordo com o model que eu importei: Filme são filmes, Episódios são episódios...


class DetalhesFilme(LoginRequiredMixin, DetailView): # exibir detalhes do filme, como imagem, nome, descrição, data de criação
    template_name = "detalhesfilme.html"
    model = Filme  # o nome do objeto é padrão object. um objeto.

    def get_context_data(self, **kwargs): # função padrão da estrutura Class Based View para adicionar um lista relacionada em UMA determinada view, nesse caso a DetailView
        context = super(DetalhesFilme, self).get_context_data(**kwargs) # linha de código obrigatória

        filmes_relacionados = Filme.objects.filter(categoria=self.get_object().categoria)[0:5]  # filtrar a tabela de filmes pegando os filmes que a categoria é a mesma do filme da página(object) pegando até 5. ex: programação, análises, apresentação.
        context["filmes_relacionados"] = filmes_relacionados # variável filmes_relacionados com a chave do dicionário filmes_relacionados que vai para o html

        return context

    def get(self, request, *args, **kwargs):  # função para pegar quando alguém entrou na página do filme e contabilizar uma visualização
        filme = self.get_object() # filme que o usuário está acessando
        filme.visualizacoes += 1
        filme.save() # salvo no banco de dados que o filme foi acessado e adicionado uma vizualização

        usuario = request.user  # pego o usuário que está logado
        usuario.filmes_vistos.add(filme)  # adiciono um campo do banco de dados com o filme que o usuário entrou na página e contabilizou como uma visuzalização

        return super(DetalhesFilme, self).get(request, *args, **kwargs) # redireciona o usuário para a url final

class Pesquisafilme(LoginRequiredMixin, ListView): # o resultado é uma lista de itens
    template_name = "pesquisa.html"
    model = Filme

    def get_queryset(self):  # função para buscar/filtrar uma informação no campo de pesquisa
        termo_pesquisa = self.request.GET.get('query') # pego o que tiver no parâmetro query lá do formulário do campo de pesquisa no navbar.html

        if termo_pesquisa:
            object_list = self.model.objects.filter(titulo__icontains=termo_pesquisa)   # nome padrão do que vem de uma ListView. self.model já referencia o model Filme da classe. titulo__icontains procura na lista o que tem parecido com aquele termo, no caso o que está na variável termo_pesquisa que vem do campo de pesquisa
            return object_list
        else:
            return None


class Paginaperfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('filme:homefilmes')


class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save() # verifica se as informações foram preenchidas corretamente e salva no banco de dados
        return super().form_valid(form)

    def get_success_url(self):  # se o formulário de criação estiver certo, o que vai ser feito
        return reverse('filme:login') # a função pede como resposta o texto de um link (reverse)





# def homepage(request):    # estrura Function Based View
#     return render(request, "homepage.html")  # retorna um template/página html. request é padrão do render

# def homefilmes(request):
#     context = {}
#     lista_filmes = Filme.objects.all() # pego todos os itens do models Filme
#     context['lista_filmes'] = lista_filmes # cria uma chave de dicionário
#     return render(request, "homefilmes.html", context) # context é uma forma usando view com uma lista/dicionário

filme/templates/criarconta.html
<!-- estou pegando o template base do arquivo base.html. as informações nos blocos entre chaves e percentual são substituídas -->
{% extends 'base.html' %}
{% load static %} <!-- carregar arquivo da pasta static -->
{% load crispy_forms_tags %} <!-- ativação do crispy do bootstrap -->

{% block titulo %}
Criar Conta
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                {{ form|crispy }}
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
        </form>

    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2021</li>
        <li> Feito com Python (Django)</li>
        <li>Hashtag</li>
    </ul>
</footer>
{% endblock %}

filme/templates/detalhesfilme.html
<!-- estou pegando o template base do arquivo base.html. as informações nos blocos entre chaves e percentual são substituídas -->
{% extends 'base.html' %}

{% block titulo %}
HomeFilmes Hashflix
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');"> <!-- seção de destaque do filme que eu entrei. caminho da imagem do filme que eu quero -->
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{ object.titulo }} <!-- object é a variável padrão da classe Homefilmes. pego a informação do campo titulo do banco de dados do filme em questão -->
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ object.descricao|slice:":100" }}... <!-- pego a informação do campo descrição do banco de dados do filme em questão. |slice corta o texto em até 100 caracteres -->
            </p>
            <div class="flex my-4"> <!-- botão de play -->
                <a href="{{ object.episodios.first.video }}"> <!-- object.episodios é a lista de episódios, filtrando pelo primeiro para ser o primeiro episódio e variável video do models Episodio -->
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'> <!-- seção da descrição e episódios -->
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-3xl font-medium">
                Descrição
            </h2>
            <div class="flex justify-left  items-center min-w-full  movie_lis">
                <p class="text-gray-100 text-lg">
                    {{ object.descricao }} <!-- pego a informação do campo descrição do banco de dados do filme em questão -->
                    <br>
                    Visualizações: {{ object.visualizacoes }}
                </p>
            </div>

            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Episódios
                </h2>
                {% for episodio in object.episodios.all %} <!-- pego todos os episódios da lista de episódios -->
                    <h3 class='text-lg'>
                        <a href="{{ episodio.video }}"> <!-- variável video do models Episodio -->
                            <p>Episódio {{ forloop.counter }}: {{ episodio.titulo }}</p> <!-- forloop.counter é estrutura do django pra fazer contagem a partir do 1 -->
                        </a>
                    </h3>
                {% endfor %}
            </div>
        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'> <!-- seção dos filmes relacionados -->
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Relacionados
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for filme in filmes_relacionados %} <!-- filmes_relacionados já é uma lista, por isso não precisa do .all -->
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'filme:detalhesfilme' filme.pk %}"> <!-- url de uma view específica. url do projeto filme namespace='filme' do hashflix/urls.py chamando name='detalhesfilme' do filme/urls.py com o id/pk do filme -->
                        <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt=""> <!-- caminho da imagem do filme que eu quero. começa com .filme ao invés de object porque está dentro do for -->
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>
{% endblock %}

filme/templates/editarperfil.html
<!-- estou pegando o template base do arquivo base.html. as informações nos blocos entre chaves e percentual são substituídas -->
{% extends 'base.html' %}
{% load static %} <!-- carregar arquivo da pasta static -->
{% load crispy_forms_tags %} <!-- ativação do crispy do bootstrap -->

{% block titulo %}
Editar Perfil
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2 class="text-2xl">{{ user.username }}</h2>
        <form method="post">
           {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
              {{ form|crispy }}
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
        </form>
        <small><a href="{% url 'filme:mudarsenha' %}">Quer mudar sua senha?</a></small>
    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2021</li>
        <li> Feito com Python (Django)</li>
        <li>Hashtag</li>
    </ul>
</footer>
{% endblock %}

filme/templates/homefilmes.html
<!-- estou pegando o template base do arquivo base.html. as informações nos blocos entre chaves e percentual são substituídas -->
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
HomeFilmes Hashflix
{% endblock %}

{% block head %} <!-- bloco de estilo css do carrossel -->
<style>
    $itemGrow: 1.2;
$duration: 250ms;

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

h1 {
  font-family: Arial;
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    display: grid;
    grid-template-columns: repeat(5, auto);
    margin: 20px 0;

    .item {
      padding: 0 2px;
      transition: $duration all;

      &:hover {
        margin: 0 40px;
        transform: scale(1.2);
      }

    }

    a {
      position: absolute;
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      width: 80px;
      padding: 20px;
      text-align: center;
      z-index: 1;

      &:nth-of-type(1) {
        top:0; bottom:0; left:0;
        background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      &:nth-of-type(2) {
        top:0; bottom:0; right: 0;
        background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }

    }

  }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
  a.arrow__btn {
    display:none;
  }
}
</style>
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ filme_destaque.thumb.url }}');"> <!-- seção do filme em destaque -->
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{ filme_destaque.titulo }}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ filme_destaque.descricao }}
            </p>
            <div class="flex my-4">
                <a href="{% url 'filme:detalhesfilme' filme_destaque.pk %}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium " >
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'> <!-- seção de novos filmes -->
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Novo
            </h2>
            <div class="wrapper">
              <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8"> <!-- primeira seção do carrossel de novos filmes -->
                <a href="#section2" class="arrow__btn text-6xl page">‹</a> <!-- o id me permite acessar a seção sem trocar de página -->
                  {% for filme in lista_filmes_recentes %}
                    {% if forloop.counter < 5 %} <!-- estipulei que cada carrossel mostra 4 filmes, se tiver menos que 5 eles são mostrados -->
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}"> <!-- url de uma view específica. url do projeto filme namespace='filme' do hashflix/urls.py chamando name='detalhesfilme' do filme/urls.py com o id/pk do filme -->
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover"> <!-- caminho da imagem do filme que eu quero -->
                          </a>
                      </div>
                    {% endif %}
                  {% endfor %}
                    <a href="#section2" class="arrow__btn text-6xl">›</a>
              </section>
                {% if lista_filmes_recentes|length > 4 %} <!-- se a lista de filmes recentes tem mais que 4 filmes, fica disponível navegar para a próxima seção -->
                  <section id="section2" class="flex flex-nowrap items-center justify-center"> <!-- segunda seção do carrossel de novos filmes -->
                    <a href="#section1" class="arrow__btn text-6xl">‹</a> <!-- o id me permite acessar a seção sem trocar de página -->
                      {% for filme in lista_filmes_recentes %}
                        {% if forloop.counter > 4 %} <!-- estipulei que cada carrossel mostra 4 filmes, se tiver mais que 4 eles são mostrados -->
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}"> <!-- url de uma view específica. url do projeto filme namespace='filme' do hashflix/urls.py chamando name='detalhesfilme' do filme/urls.py com o id/pk do filme -->
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover"> <!-- caminho da imagem do filme que eu quero -->
                              </a>
                          </div>
                        {% endif %}
                      {% endfor %}
                    <a href="#section1" class="arrow__btn text-6xl">›</a>
                  </section>
                {% endif %}
            </div>
        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'> <!-- seção de em alta -->
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Em Alta
            </h2>
            <div class="wrapper">
              <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8"> <!-- primeira seção do carrossel de novos filmes -->
                <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a> <!-- o id me permite acessar a seção sem trocar de página -->
                  {% for filme in lista_filmes_em_alta %}
                    {% if forloop.counter < 5 %} <!-- estipulei que cada carrossel mostra 4 filmes, se tiver menos que 5 eles são mostrados -->
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}"> <!-- url de uma view específica. url do projeto filme namespace='filme' do hashflix/urls.py chamando name='detalhesfilme' do filme/urls.py com o id/pk do filme -->
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover"> <!-- caminho da imagem do filme que eu quero -->
                          </a>
                      </div>
                    {% endif %}
                  {% endfor %}
                    <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
              </section>
                {% if lista_filmes_em_alta|length > 4 %} <!-- se a lista de filmes recentes tem mais que 4 filmes, fica disponível navegar para a próxima seção -->
                  <section id="section2emalta" class="flex flex-nowrap items-center justify-center"> <!-- segunda seção do carrossel de novos filmes -->
                    <a href="#section1emalta" class="arrow__btn text-6xl">‹</a> <!-- o id me permite acessar a seção sem trocar de página -->
                      {% for filme in lista_filmes_em_alta %}
                        {% if forloop.counter > 4 %} <!-- estipulei que cada carrossel mostra 4 filmes, se tiver mais que 4 eles são mostrados -->
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}"> <!-- url de uma view específica. url do projeto filme namespace='filme' do hashflix/urls.py chamando name='detalhesfilme' do filme/urls.py com o id/pk do filme -->
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover"> <!-- caminho da imagem do filme que eu quero -->
                              </a>
                          </div>
                        {% endif %}
                      {% endfor %}
                    <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                  </section>
                {% endif %}
            </div>
        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'> <!-- seção de continuar assistindo -->
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Continuar Assistindo
            </h2>
            <div class="wrapper">
              <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8"> <!-- primeira seção do carrossel de novos filmes -->
                <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a> <!-- o id me permite acessar a seção sem trocar de página -->
                  {% for filme in request.user.filmes_vistos.all %}
                    {% if forloop.counter < 5 %} <!-- estipulei que cada carrossel mostra 4 filmes, se tiver menos que 5 eles são mostrados -->
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}"> <!-- url de uma view específica. url do projeto filme namespace='filme' do hashflix/urls.py chamando name='detalhesfilme' do filme/urls.py com o id/pk do filme -->
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover"> <!-- caminho da imagem do filme que eu quero -->
                          </a>
                      </div>
                    {% endif %}
                  {% endfor %}
                    <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
              </section>
                {% if request.user.filmes_vistos.all|length > 4 %} <!-- se a lista de filmes recentes tem mais que 4 filmes, fica disponível navegar para a próxima seção -->
                  <section id="section2vistos" class="flex flex-nowrap items-center justify-center"> <!-- segunda seção do carrossel de novos filmes -->
                    <a href="#section1vistos" class="arrow__btn text-6xl">‹</a> <!-- o id me permite acessar a seção sem trocar de página -->
                      {% for filme in request.user.filmes_vistos.all %}
                        {% if forloop.counter > 4 %} <!-- estipulei que cada carrossel mostra 4 filmes, se tiver mais que 4 eles são mostrados -->
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}"> <!-- url de uma view específica. url do projeto filme namespace='filme' do hashflix/urls.py chamando name='detalhesfilme' do filme/urls.py com o id/pk do filme -->
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover"> <!-- caminho da imagem do filme que eu quero -->
                              </a>
                          </div>
                        {% endif %}
                      {% endfor %}
                    <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
                  </section>
                {% endif %}
            </div>
        </div>
    </section>
</main>

{% endblock %}

filme/templates/pesquisa.html
<!-- estou pegando o template base do arquivo base.html. as informações nos blocos entre chaves e percentual são substituídas -->
{% extends 'base.html' %}

{% block titulo %}
Pesquisa de Filmes
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Resultados da Busca
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis"> <!-- lista de resultados -->
              {% for filme in object_list %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                      <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                    </a>
                </div>
              {% endfor %}
            </div>


        </div>
    </section>
</main>
{% endblock %}