filme/urls.py
from django.urls import path, reverse_lazy
from .views import Homepage, Homefilmes, DetalhesFilme, Pesquisafilme, Paginaperfil, Criarconta
from django.contrib.auth import views as auth_view  # dei novo nome para não confundir com as outras views que existem

app_name = 'filme' # nome do app para chamar nas urls do projeto hashflix, e não do projeto filme

urlpatterns = [
    # path('', homepage),  # caminho padrão do site, sem parâmetro na url. estou incluindo uma view chamada homepage. ou seja, chama a função homepage no arquivo views.py. estrutura Function Based View
    path('', Homepage.as_view(), name='homepage'), # chamo a classe Homepage como uma view do arquivo views.py. estrutura Class Based View
    path('filmes/', Homefilmes.as_view(), name='homefilmes'), # caminho para a tela de filmes, chamando a classe Homefilmes. name é para chamar a url nas tags <a href>
    path('filmes/<int:pk>', DetalhesFilme.as_view(), name='detalhesfilme'),  # chave primária do filme que eu quero, já que vem do object do model Detalhesfilme. caminho para a tela de detalhe do filme
    path('pesquisa/', Pesquisafilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),  # LoginView é padrão do django, não precisei criar no views.py
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html', success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'), # uso a editarperfil porque as funcionalidades das páginas são as mesmas
]

hashflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # permite achar o caminho da pasta static
from django.conf.urls.static import static  # permite achar o caminho da pasta static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme')),  # essa path está sendo o caminho padrão do site. namespace filme engloba todas as urls do app filme (variável app_name criada no filme/urls.py)
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # link para os arquivos static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # link para os arquivos media

templates/base.html
<!-- arquivo de template base para todos os outros html. evita ficar repetindo código. as outras páginas extendem essa através dos blocos entre chaves e percentual -->

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}
        {% endblock %}
    </title>                                             <!-- script para ativar as edições em bootstrap (editor de html/css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>  <!-- script para ativar as edições em tailwind (editor de html/css -->

    {% block head %}
    {% endblock %}
</head>
<body class="bg-black text-gray-100 font-primary">  <!-- classes do bootstrap para deixar fundo preto-->
    {% include 'navbar.html' %}  <!-- incluo as edições da página navbar.hmtl -->
    {% block content %}
    {% endblock %}
                        <!-- meu código js para editar a barra de navegação -->
    <script>
        const nav = document.querySelector('nav') <!-- variável para selecionar as tags nav nos html -->

        document.addEventListener("scroll",e=>{ <!-- executa sempre que fizer um scroll no mouse -->
            if(scrollY>100){  <!-- se o scroll for maior que 100 -->
                if(scrollY>window.innerHeight){  <!-- se o scroll for maior que a tela, a barra de navegação fica invisível -->
                nav.classList.add('invisible')
                }else{
                    nav.classList.add('bg-gray-900')  <!-- senão fica cinza -->
                    nav.classList.remove('invisible')
            }
            }else{
                nav.classList.remove('bg-gray-900')
                nav.classList.remove('invisible')
            }
        })
    </script>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script> <!-- scripts para usar os símbolos do ion-icon -->
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>

templates/navbar.html
{% load static %} <!-- carregar arquivo da pasta static -->

<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50"> <!-- tailwind. barra de navegação ter a largura da página inteira. flex justify distribui os objetos. padding coloca espaço nas bordas. fixa no topo. z mantém as coisas na frente ou atrás das outras -->
    <div class="w-6/12"> <!-- tailwind. divide a navegação ao meio, com largura 6 de 12 -->
        <a href="/">
           <img class="w-2/12" src="{% static 'images/hashflix.png' %}"> <!-- a imagem ocupa 5 espaços do primeiro div. bloco de estrutura do arquivo settings para buscar um arquivo static (imagem) -->
        </a>
    </div>

    <div class="w-6/12 flex flex-nowrap justify-end"> <!-- tailwind. divide a navegação ao meio, com largura 6 de 12. flex nowrap não quebra linha dos objetos no flex, fica um do lado do outro. justify-end alinha no final da tela -->
        {% if user.is_authenticated %} <!-- mostra a pesquisa, login e editar perfil apenas se o usuário estiver logado -->
        <div class="mr-2"> <!-- margin right de 2px. 1º div pra pesquisar -->
            <form method="get" action="{% url 'filme:pesquisafilme' %}"> <!-- filme é do namespace em hashflix/urls.py e pesquisafilme é name do filme/urls.py -->
                <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar..."> <!-- tailwind. padding. arredondar bordas. name="query" é o parâmetro que vai para a barra de pesquisa da url quando digita alguma coisa na busca. value pega a requisição do query e mantém escrito no campo de pesquisa -->
                <input type="submit" value="">
            </form>
        </div>
        {% endif %}
        <div class="mr-2"> <!-- margin right de 2px. 2º div para sair -->
            {% if user.is_authenticated %} <!-- se estiver logado, mostra o botão sair -->
            <a href="{% url 'filme:logout' %}"> <!-- leva para a url de logout -->
                <button class="bg-red-600 text-white py-1 px-3 rounded-md"> <!-- tailwind -->
                    Sair
                </button>
            </a>
            {% else %} <!-- se não estiver logado, mostra o botão login -->
            <a href="{% url 'filme:login' %}"> <!-- leva para a url de login -->
                <button class="bg-red-600 text-white py-1 px-3 rounded-md"> <!-- tailwind -->
                    Login
                </button>
            </a>
            {% endif %}
        </div>
        {% if user.is_authenticated %} <!-- mostra a pesquisa, login e editar perfil apenas se o usuário estiver logado -->
        <div class="mr-2"> <!-- margin right de 2px. 3º div para editar perfil -->
            <a href="{% url 'filme:editarperfil' user.pk %}"> <!-- leva para a url de editar perfil -->
                <button class="bg-red-600 text-white py-1 px-3 rounded-md"> <!-- tailwind -->
                    Editar Perfil
                </button>
            </a>
        </div>
        {% endif %}
    </div>
</nav>